services:
  # locally hosted prover network
  hierophant:
    # You're welcome to build your own image and use it here instead: https://github.com/unattended-backpack/hierophant/
    image: jossduff/hierophant:latest
    entrypoint: /start-hierophant.sh
    env_file:
      - .env
    volumes:
      - ./docker/start-hierophant.sh:/start-hierophant.sh
    ports:
      - ${PORT__HIEROPHANT_HTTP}:${PORT__HIEROPHANT_HTTP}
      - ${PORT__HIEROPHANT_GRPC}:${PORT__HIEROPHANT_GRPC}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # creates contemplant instances on vast.ai who execute proofs for Hierophant
  magister:
    # You're welcome to build your own image and use it here instead: https://github.com/unattended-backpack/magister
    image: jossduff/magister:latest
    entrypoint: /start-magister.sh
    env_file:
      - .env
    volumes:
      - ./docker/start-magister.sh:/start-magister.sh
    ports:
      - ${PORT__MAGISTER_HTTP}:${PORT__MAGISTER_HTTP}
    environment:
      # Number of prover (`contemplant`) instances to run
      - NUMBER_INSTANCES=${NUMBER_PROVERS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - hierophant
    restart: unless-stopped
